// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddressItem: typeof import('./src/components/shop/AddressItem.vue')['default']
    Carts: typeof import('./src/components/shop/Carts.vue')['default']
    CartsItem: typeof import('./src/components/shop/CartsItem.vue')['default']
    Goods: typeof import('./src/components/shop/Goods.vue')['default']
    GoodsItem: typeof import('./src/components/shop/GoodsItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    OrderRow: typeof import('./src/components/order/OrderRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/swiper/Side.vue')['default']
    Tab: typeof import('./src/components/tab/Tab.vue')['default']
    TabPane: typeof import('./src/components/tab/TabPane.vue')['default']
    Verify: typeof import('./src/components/input/verify.vue')['default']
  }
}
